"""Resolve one runtime's Windows CPython 3.11 wheels into a hash lock.

This script is only for release/build preparation. Production launchers never
call pip and never look at the network.
"""
from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
import zipfile
from pathlib import Path
from pathlib import PurePosixPath


def metadata_from_wheel(path: Path) -> tuple[str, str]:
    with zipfile.ZipFile(path) as archive:
        metadata_paths = [
            name
            for name in archive.namelist()
            if len(PurePosixPath(name).parts) == 2
            and PurePosixPath(name).parts[0].endswith(".dist-info")
            and PurePosixPath(name).parts[1] == "METADATA"
        ]
        if len(metadata_paths) != 1:
            raise ValueError(f"wheel has no single METADATA file: {path.name}")
        metadata = archive.read(metadata_paths[0]).decode("utf-8")
    name = next((line[6:] for line in metadata.splitlines() if line.startswith("Name: ")), None)
    version = next((line[9:] for line in metadata.splitlines() if line.startswith("Version: ")), None)
    if not name or not version:
        raise ValueError(f"wheel has no Name/Version metadata: {path.name}")
    return name, version


def digest(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            value.update(chunk)
    return value.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("runtime")
    parser.add_argument("--requirements-root", type=Path, required=True)
    parser.add_argument("--wheelhouse-root", type=Path, required=True)
    parser.add_argument("--source-wheelhouse", type=Path)
    parser.add_argument("--python", default=sys.executable)
    arguments = parser.parse_args()
    source = arguments.requirements_root / f"{arguments.runtime}.in"
    lock = arguments.requirements_root / f"{arguments.runtime}.lock"
    wheelhouse = arguments.wheelhouse_root / arguments.runtime
    if not source.is_file():
        raise SystemExit(f"requirements input is missing: {source}")
    wheelhouse.mkdir(parents=True, exist_ok=True)
    command = [
        arguments.python, "-B", "-I", "-m", "pip", "download", "--dest", str(wheelhouse), "--only-binary", ":all:",
    ]
    if arguments.source_wheelhouse is not None:
        command.extend(("--no-index", "--find-links", str(arguments.source_wheelhouse)))
    else:
        command.extend(("--find-links", str(wheelhouse)))
    command.extend((
        "--platform", "win_amd64", "--implementation", "cp", "--python-version", "311", "--abi", "cp311", "-r", str(source),
    ))
    subprocess.run(command, check=True)
    wheels = sorted(wheelhouse.glob("*.whl"), key=lambda item: item.name.lower())
    entries: list[tuple[str, str, str]] = []
    for wheel in wheels:
        name, version = metadata_from_wheel(wheel)
        entries.append((name.lower().replace("_", "-"), version, digest(wheel)))
    lines = [
        "# Generated by packaging/scripts/resolve_wheels.py; do not edit manually.",
        "# Windows x64, CPython 3.11 wheels only.",
    ]
    for name, version, sha256 in sorted(entries):
        lines.append(f"{name}=={version} --hash=sha256:{sha256}")
    if not entries:
        lines.append("# No third-party production dependencies for this runtime.")
    lock.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
